form/urls.py
from django.conf.urls import url

from . import views

app_name = 'form'
urlpatterns = [
    url(r'^$', views.feedback_form, name='home'),
]

hire/urls.py
from django.conf.urls import url
from django.urls.conf import path
from hire import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'hire'

urlpatterns = [
    url(r'^$', views.hire_form, name='hireform'),
    # path('', views.index1, name='hirePage'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

lendingSystem1/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url 

from users import views as user_views
from sellItem import views as sell_views
from hire import views as hire_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user_views.home, name='home'),
    path('home/',user_views.home, name='home'),
    path('signup/', user_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name='logout'),
    url(r'^feedback_form/', include('form.urls')),
    path('feedback_form/', user_views.addlend, name='feedback'),
    url(r'^homepage/', include('homepage.urls')),
    path('homepage/', user_views.homePage, name='homepage'),
    url(r'^thirdpartyform/', include('sellItem.urls')),
    path('thirdpartyform/', sell_views.item_form, name='thirdpartyform'),
    url(r'^hireform/', include('hire.urls')),
    path('hireform/', hire_views.hire_form, name='hireform'),
    # url(r'^hirePage/', include('hire.urls')),
    # path('hirePage/', hire_views.hirePage, name='hirePage'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ObjectDoesNotExist

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):

    try:
        instance.profile.save()
    except ObjectDoesNotExist:
        Profile.objects.create(user=instance)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    first_name = forms.CharField(max_length=50, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=50, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=120, help_text='Required. Enter a valid email address.')
    birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'birth_date', 'password1', 'password2')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .forms import SignupForm



def home(request):
    return render(request, 'users/home.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.birth_date = form.cleaned_data.get('birth_date')
            user.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignupForm()

    context = {'form': form}
    return render(request, 'users/signup.html', context)

def addlend(request):
    return redirect('feedback_form')

def homePage(request):
    return redirect('homepage')

users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>User Authentication System</title>

    {% block style %}
    {% endblock style %}
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

users/templates/users/home.html
{% extends 'users/base.html' %}
{% block style %}
    <style>
        h1 {
            text-align: center;
        }
        a {
            display: inline-block;
            background: #313030;
            color: #FFF;
            border: 0;
            border-radius: 4px;
            text-align: center;
            padding: 20px 30px;
            line-height: 1;
            text-decoration: none;
        }
        a:hover {
          background: #c7c5c5;
          color: #313030;
        }
        .a2 {
            margin-left: 1em;
        }
        .center {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 200px;
            border: 3px solid #313030;
        }
    </style>
{% endblock style %}

{% block content %}
    <br>
    {% if user.is_authenticated %}
        <div class="alert alert-success" role="alert">
            <h1>Welcome {{ user.username }}!</h1>
        </div>
    {% else %}
        <div class="alert alert-success" role="alert">
            <h1>Welcome to Authentication System!</h1>
        </div>
    {% endif %}
    <br>

{
    <div class="center">
        {% if user.is_authenticated %}
            <a class="a2" href="{% url 'homepage' %} ">See Items</a>
            <a class="a2" href="{% url 'feedback' %} ">Give Feedback</a>
            <a class="a2" href="{% url 'thirdpartyform' %} ">Post an Ad</a>
            <a class="a2" href="{% url 'hire:hireform' %} ">Post Hire Ad</a>


            <a class="a2" href="{% url 'logout' %} ">Logout</a>
        {% else %}
            <a class="a1" href="{% url  'signup' %}">Sign Up</a>
            <a class="a2" href="{% url 'login' %}">Login</a>
        {% endif %}
    </div>
{% endblock content %}

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
  <br>
  <div class="alert alert-success" role="alert">
    <h2 style="text-align: center;">Login</h2>
  </div>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock content%}

users/templates/users/logout.html
{% extends 'users/base.html' %}

{% block content %}
    <br>
    <div class="alert alert-success" role="alert">
        <h2 style="text-align: center;">Logged out!</h2>
    </div>

    <h3>Login again?</h3>
    <a href="{% url 'login' %}">---> Login</a> <br>
    <a href="{% url 'home' %}"><--- Or go back to home.</a>
{% endblock content %}

users/templates/users/signup.html
{% extends 'users/base.html' %}

{% block content %}
    <br>
    <div class="alert alert-success" role="alert">
        <h3 style="text-align: center;">Sign Up</h3>
    </div>
    <br>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
            {% endfor %}
        </p>
        {% endfor %}
        <button type="submit">Sign up</button>
    </form>
{% endblock content%}