form/urls.py
from django.conf.urls import url

from . import views

app_name = 'form'
urlpatterns = [
    url(r'^$', views.feedback_form, name='home'),
]

lendingSystem1/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url 

from users import views as user_views
from sellItem import views as sell_views
from hire import views as hire_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user_views.home, name='home'),
    path('home/',user_views.home, name='home'),
    path('signup/', user_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name='logout'),
    url(r'^feedback_form/', include('form.urls')),
    path('feedback_form/', user_views.addlend, name='feedback'),
    url(r'^homepage/', include('homepage.urls')),
    path('homepage/', user_views.homePage, name='homepage'),
    url(r'^thirdpartyform/', include('sellItem.urls')),
    path('thirdpartyform/', sell_views.item_form, name='thirdpartyform'),
    url(r'^hireform/', include('hire.urls')),
    path('hireform/', hire_views.hire_form, name='hireform'),
    # url(r'^hirePage/', include('hire.urls')),
    # path('hirePage/', hire_views.hirePage, name='hirePage'),

]

form/models.py
from django.db import models




class Feedback(models.Model):
    customer_name = models.CharField(max_length=120)
    email = models.EmailField()
    details = models.TextField()
    happy = models.BooleanField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.customer_name

form/forms.py
from django import forms

from .models import Feedback


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        exclude = []

form/views.py
from django.shortcuts import render

from .forms import FeedbackForm


def feedback_form(request):
    if request.method == 'POST':
        form= FeedbackForm(request.POST)

        if form.is_valid():
            form.save()
            return render(request, 'form/thanks.html')
    else:
        form = FeedbackForm()
    return render(request, 'form/feedback_form.html', {'form': form})

form/templates/form/base1.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

form/templates/form/feedback_form.html
{% extends 'form/base1.html' %}

{% block title %}Feedback Form{% endblock %}

{% block body %}
<form action="{% url 'form:home' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" />
</form>
{% endblock %}

form/templates/form/thanks.html
{% extends 'form/base1.html' %}

{% block title %}Thanks{% endblock %}

{% block body %}
<h1>Thanks for your response.</h1>
<p><a href="{% url 'form:home' %}">Response again?</a></p>
{% endblock %}